services:
  indextts-cuda:
    image: ghcr.io/seancheung/indextts-openai-tts-api:cuda-latest
    ports:
      - "8000:8000"
    volumes:
      - ./voices:/voices:ro
      - ./hf_cache:/root/.cache/huggingface
    environment:
      INDEXTTS_MODEL: "IndexTeam/IndexTTS-2"
      INDEXTTS_USE_FP16: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  indextts-cpu:
    image: ghcr.io/seancheung/indextts-openai-tts-api:latest
    ports:
      - "8010:8000"
    volumes:
      - ./voices:/voices:ro
      - ./hf_cache:/root/.cache/huggingface
    environment:
      INDEXTTS_MODEL: "IndexTeam/IndexTTS-2"
